### ISSUE TITLE
java.lang.IllegalStateException: Can't stop an already stopped recording.

### ISSUE THREAD

**Issue by ales-ondrus** [mirkosertic/flight-recorder-starter#4]
**Steps to reproduce**
* run command `curl  -i -X PUT -H "Content-Type: application/json" -d '{"duration": "60","timeUnit":"SECONDS"}' http://localhost:8080/actuator/flightrecorder`
* after 65 seconds run command `curl --output recording.jfr http://localhost:8080/actuator/flightrecorder/1`

**Output**

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   156    0   156    0     0   1974      0 --:--:-- --:--:-- --:--:--  1974
```

```json
{
	"timestamp": "2020-11-04T13:16:28.303+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"message": "",
	"path": "/actuator/flightrecorder/1"
}
```

**Log**

```
java.lang.IllegalStateException: Can't stop an already stopped recording.
	at jdk.jfr/jdk.jfr.internal.PlatformRecorder.stop(PlatformRecorder.java:262)
	at jdk.jfr/jdk.jfr.internal.PlatformRecording.stop(PlatformRecording.java:157)
	at jdk.jfr/jdk.jfr.Recording.stop(Recording.java:210)
	at de.mirkosertic.flightrecorderstarter.FlightRecorder.stopRecording(FlightRecorder.java:68)
	at de.mirkosertic.flightrecorderstarter.FlightRecorderEndpoint.downloadRecording(FlightRecorderEndpoint.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Cause**

* before stopping recording `recording.stop()`
* you need to check recording state
* if recording is already done then `IllegalStateException` is thrown according to the documentation
* and it is not possible to download JFR file

``` java
    public File stopRecording(final long recordingId) {
        final Recording recording = recordings.get(recordingId);
        if (recording != null) {
              //
              // IllegalStateException if already stopped - check state before calling this method
              //
            recording.stop();
            return recording.getDestination().toFile();
        } else {
            LOGGER.log(Level.WARNING, "No recording with id {0} found", recordingId);
            return null;
        }
    }
```

**Workaround**

* call `curl --output recording.jfr http://localhost:8080/actuator/flightrecorder/1` during recording
* before elapsed time defined by period `{"duration": "60","timeUnit":"SECONDS"}`

<hr>

Thank you for creating this piece of code. It is exactly what I need.

**Comment by mirkosertic** [comment]
Thank you for this very detailied bug report.

I've release version 1.1.1 including a fix for this issue.
